#!/usr/bin/env python3
from src.core.runtime import run
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-p","--projects",
            help="one or more projects to be run",
            nargs='+',default="all")
    parser.add_argument("-w","--wrap",
            help="specify that projects should be run in 'wrapped' mode",
            action='store_true')
    args = parser.parse_args()
    return vars(args)

def main():
    args = parse_args()
    run(proj=args['projects'],wrap=args['wrap'])

if __name__ == '__main__':
    main()
